name: Generate functions
on: push
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
              env:
                    FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hello', 'World')}} #format
                    JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} #join